# 4절 복사와 뷰

## 4.1 할당

In [1]:
# 스칼라 변수
a = 10
b = a
id(a),id(b)

(2298821345808, 2298821345808)

## 4.2 뷰(View)

In [4]:
import numpy as np
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
c = a.view()
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
c==a

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [7]:
np.all(c==a)

True

In [8]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
c.shape = (2,6)
c

array([[ 0,  1,  2,  3, -9,  5],
       [-9,  7,  8,  9, 10, 11]])

In [14]:
c[1, ::2] = -9
c

array([[ 0,  1,  2,  3, -9,  5],
       [-9,  7, -9,  9, -9, 11]])

In [15]:
# 슬라이싱이 될 때 뷰가 반환됨
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])