<b><font color="red" size="6"> ch11. N차원 배열 다루기 </font></b>
- [numpy](https://numpy.org/)
- [numpy docs](https://numpy.org/doc/stable/user/absolute_beginners.html)
- N차원 배열 객체
- 2차원 배열은 행렬개념으로 이해
- numpy 패키지를 이용(c언어로 구현된 고성능 수치계산 패키지)

# 1절. 넘파이 패키지

In [1]:
import numpy as np
np.__version__

'1.23.5'

In [2]:
a = np.arange(15) # 0부터 15앞까지 1씩 증가하는 1차원 배열
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
from numpy import arange
a = arange(15, 30).reshape(3, 5) # 3행 5열짜리 2차원 배열
a

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [4]:
type(a) # a배열변수의 타입

numpy.ndarray

In [5]:
a.dtype # a배열변수의 요소들의 type

dtype('int32')

In [6]:
a.dtype.name

'int32'

In [7]:
a.itemsize # 한 요소의 bytesize(int32의 경우 : 4byte)

4

In [8]:
a.ndim # 축의 수 (차원수)

2

In [9]:
a.size # 배열 요소의 갯수

15

In [10]:
a.shape # 배열의 구조(3행 5열)

(3, 5)

In [11]:
print('구조 조정 전 a:\n',a)
a.shape = (5, 3)
print('shape 수정후 a:\n',a)

구조 조정 전 a:
 [[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
shape 수정후 a:
 [[15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]


In [12]:
a.shape=()

ValueError: cannot reshape array of size 15 into shape ()

In [ ]:
# 배열 요소의 타입을 수정
a = np.arange(12).reshape(3,4)
a

In [ ]:
a.size # 요소의갯수

In [ ]:
a.dtype

In [ ]:
a.itemsize

In [ ]:
a.dtype = np.int64
a.dtype

In [ ]:
a.itemsize #요소의 byte 사이즈

In [ ]:
a.size

In [ ]:
a

In [ ]:
a.ravel() # flatten 됨()

# 2절. 넘파이 배열
- array() 함수를 이용한 다른 파이썬 구조(list, tuple)
- 기타 함수들 : arange, ones, zeros, empty
- 랜덤값을 갖는 함수들....
- [넘파이 doc](https://numpy.org/doc/stable/user/absolute_beginners.html)
- [넘파이 함수들](https://numpy.org/doc/stable/reference/index.html#reference)

## 2.1 array()함수로 넘파이 배열 만들기
- array(obj, dtype=np.(타입), copy=T/F)

In [ ]:
a = np.array([2, 4, 6], dtype=np.int16) # 정수의 기본타입 int32
a

In [ ]:
a[0], a[1], a[2]

In [ ]:
for i in a:
    print(i, end='\t')

In [ ]:
a.dtype

In [ ]:
b = np.array([[1.5, 2.3], #실수의 기본 타입은 float64
             [4,5]])      # 동일 자료형으로 배열 생성 : 정수 -> 실수 -> 문자
b

In [ ]:
b[0][0], b[0,0] # 2차원 (axis0행, axis1열)

In [ ]:
b = np.array([(1.5, 2.3), #실수의 기본 타입은 float64
             (4,5)])      # 동일 자료형으로 배열 생성 : 정수 > 실수 > 문자
b

In [ ]:
a = np.array([[1.5, 2.3],[4,5]]).reshape(1,4) # 2행 2열짜리 배열을 1행 4열로 shape 변환
a

In [ ]:
a.dtype

In [ ]:
a = np.array([1.5, 2.3,4,5],dtype=np.float32).reshape(2,2)
a

In [ ]:
a.itemsize # 한 요소의 byte 수

In [ ]:
a.dtype

In [ ]:
# a.dtype = np.float64 하면 안됨
a = a.astype(np.float64) # 배열 요서의 타입을 바꾸는 함수
a

In [ ]:
a.dtype

In [ ]:
l = [[1, 2],[3.4, 4.5]]
for row in l:
    for data in row:
        print(data, end='\t')
    print()

In [ ]:
for i, row in enumerate(l):
    for j, row in enumerate(row):
        print('{}행 {}열 : {}'.format(i, j, data), end='\t')
    print()

In [ ]:
print(l[0][0]) # 리스트의 인덱싱
print(l[0:2][0]) # 슬라이싱

In [ ]:
# 2챠월 배열
b = np.array([[1,2,3,4,5],[6,7,8,9,10]], dtype=np.int16)
b

In [ ]:
for row in b:
    for data in row :
        print(data, end='\t')
    print()

In [ ]:
for i, row in enumerate(b):
    for j,data in enumerate(row):
        print('{}행 {}열 : {}'.format(i,j,data), end='\t')
    print()

In [ ]:
print(b[0,0]) # 인덱싱
print(b[0:2, 1:3]) #슬라이싱

In [ ]:
print(b[0, 1:3]) # 0행을 슬라이싱 하면 1차원 배열

In [ ]:
print(b[:,-1]) # 모든 행의 마지막 열만 추출

In [ ]:
print(b[:, -2:]) #모든 행의 마지막 2열을 추출

In [ ]:
# 스칼라변수
a = 10
b = a
print('a ={}, b={}'.format(a,b))
b = -1
print('a ={}, b={}'.format(a,b))

In [ ]:
# numpy 배열
c = np.array([[1,2,], [3,4]])
d = np.array(c, copy=False) # d = c 동일 ; 얕은 복사
print('c=',c, sep='\n')
print('d=',d, sep='\n')
print('두 변수의 주소:', id(c),id(d))
d[0,0] = 9
print('c=',c, sep='\n')
print('d=',d, sep='\n')
print('c.dtype:', c.dtype,'d.dtype:', d.dtype)

In [ ]:
# numpy 배열
c = np.array([[1,2,], [3,4]])
d = np.array(c, copy=True) # d = c.copy() 동일 ; 깊은 복사
print('c=',c, sep='\n')
print('d=',d, sep='\n')
print('두 변수의 주소:', id(c),id(d))
d[0,0] = 9
print('c=',c, sep='\n')
print('d=',d, sep='\n')
print('c.dtype:', c.dtype,'d.dtype:', d.dtype)

In [ ]:
# copy=False 넣었지만 깊은 복사가 되는 경우 (타입을 다르게 지정할 경우)
c = np.array([[1,2],[3,4]], dtype=np.int32) # 기본타입이 int32
d = np.array(c, copy=False, dtype=np.int16) # dtype이 바뀌면 자동 깊은 복사
d[0,0] = 9
print('두변수의 주소 :',id(c),id(d))
print('두변수의 dtype :', c.dtype, d.dtype)
print('c=',c, sep='\n')
print('d=',d, sep='\n')

## 2.2 기본값이 있는 배열 만들기
- np.zeros(tup) : 요소들이 다 0
- np.ones(tup) : 요소들이 다 1
- np.full(tup, 기본값) : 요소들이 다 두번빼 매개변수인 기본값
- np.empty(tup) : 초기 내용은 임의값인 배열 (메모리 상태에 따라 달라짐)
※ 위 함수를 이용해서 생성된 배열은 기본 dtype이 float64. dtype 속성을 따로 지정할 수 있음

In [ ]:
np.zeros( (3,5) ) # 3행 5열짜리 2차원 float64 배열 (요소들은 다 0)

In [ ]:
x = np.zeros((2,5), dtype=np.int16)
print(x)
print(x.dtype)
print(x.itemsize) # 한 요소의 byte사이즈

In [ ]:
np.ones((2,5))

In [ ]:
np.ones((2,5), dtype=np.complex64)

In [ ]:
np.full((2,5), -1.2)

In [ ]:
np.empty((2,5))

In [ ]:
np.empty((3,2)) # 초기값이 메모리 상태에 따라 임의의 값

## 2.3 랜덤값을 갖는 배열 만들기
- np.random.random(tup) : 0부터 1미만의 균등분포를 갖는 랜덤값
- np.random.nuiform(low=0, high=1.0, size=tup) : low부터 high미만까지 균등분포를 갖는 랜덤값
- np.random.normal(loc=0.0, sclae=1.0, size=tup) : 평균 loc과 표준편차scale을 갖는 정규분포를 갖는 랜던값

- np.random.rand(n) : 균등분포의 1차원 난수 배열발생 (난수 n개) 0 부터 1미만의 실수난수
- np.random.randn(n) : 표준정규분포의 1차원 난수 배열 발생 (난수 n개)

- np.random.randint(n) : 0부터 n미만의 정수 난수 1개 발생

In [ ]:
# rand()가 균등분포(최소값~ 최대값까지 균일한 확율로 난수발생)에서 난수 발생 확인 (0~1사이)
import matplotlib.pyplot as plt
x = np.random.rand(100000)
plt.figure(figsize=(5,2)) # 그래프 크기 (가로, 세로)
plt.hist(x)
plt.show()

In [ ]:
# randn() : 표준정규분포(평균0, 표준편차1인 정규분표)에서 난수 발생
x = np.random.randn(100000)
plt.figure(figsize=(5,2)) # 그래프 사이즈 조정
plt.hist(x, bins=100)
plt.show()

In [ ]:
np.random.random((2,5)) # 2행 5열짜리 난수(0이상 1미만 균등분포 실수 난수) 배열

In [ ]:
np.random.uniform(-2, 10, (2,5)) # 최소값, 최대값 2행 5열까지 난수(-2~10미만의 균등분포 실수 난수) 배열

In [ ]:
np.random.seed(12) # seed값을 맞추면 발생되는 난수가 동일
np.random.normal(-2, 2, (2,5)) # 2행 5열짜리 평균-2, 표준편차 2인 정규분포 난수 발생

In [ ]:
# 정수 난수 1개 발생
np.random.randint(45) # 0~44 사이의 정수 난수 1개 발생(균등분포)

## 2.4 연속된 값을 갖는 배열 만들기
- np.arange(from, to, by, dtype) : from부터 to앞까지 by씩 건너뛴 값(to미포함)을 1차원 배열로 생성
- np.linspace(from, to, num) : from부터 to까지(to포함) num개 숫자들을 1차원 배열로 생성

In [ ]:
np.arange(10, 30, 5, dtype=np.float64)

In [ ]:
np.arange(0, 2.1, 0.3).reshape(2,4) # 2행 4열

In [ ]:
np.linspace(0, 2, 20)

In [ ]:
np.linspace(0, 2, 20).reshape(4,5)

In [ ]:
# linspace : 많은 수의 점들을 생성할 때 유용
from numpy import linspace, pi
x = linspace(0, 2*np.pi, 100)
f = np.sin(x)

In [ ]:
import matplotlib.pyplot as plt
plt.figure(figsize=(5,2))
plt.plot(x, f)
plt.show()

## 2.5 배열의 차원 변경하기
- reshape(행수, 열수) : -1이 올수있음
- resize((행수,열수)) : -1이 불가
- T : 전치행렬로 변환
- transpose() : 전치행렬로 변환

※ 실행결과가 출력되면 배열이 수정되지 않고, 실행결과가 없으면 배열이 수정됨

In [ ]:
t = np.random.random( (2,3) )
t

In [ ]:
a = np.floor(t*10)
a

In [ ]:
a = a.astype(np.int16)
a # 2행 3열 2차원 배열

In [ ]:
a = a.reshape(3,2) # 3행 2열로 차원변경

In [ ]:
a.reshape(-1, 3) # -1이 주어지면 해당 차원의 크기가 자동 계산

In [ ]:
a.reshape(6, -1)

In [ ]:
a.resize((2,3))
a

In [ ]:
a

In [ ]:
a.T # a의 전치행렬 (행과 열을 뒤바꾼 행렬)

In [ ]:
a.transpose() # a의 전치행렬

## 2.6 배열 인쇄

In [ ]:
# 배열이 커서 출력이 안 될 경우
print(np.arange(10000))

In [ ]:
np.arange(10000).reshape(100,100)

In [ ]:
# 배열이 너무 커서 인쇄할 수 없는 경우는 자동으로 건너뛰고 모서리 부분만 출력
# 넘파이의 인쇄 옵션 변경 (인쇄할 사이즈를 최대치)
import sys
np.set_printoptions(threshold=10000) # 배열 10000개까지 출력하도록 옵션
np.set_printoptions(threshold=sys.maxsize)
np.set_printoptions(threshold=np.inf) # np.inf는 무한대
# 커널 재시작시 다시 옵션 복귀

In [ ]:
np.arange(10000).reshape(100,100)

In [ ]:
import numpy as np
np.arange(10000).reshape(100,100)

## 2.7 기본연산 동작
### 1)배열의 요소별 연산

In [ ]:
a = np.array([20,30,40,50])
b = np.arange(4)
print(a)
print(b)

In [ ]:
a + b

In [ ]:
a ** b

In [ ]:
a += b # a = a+b
a

In [ ]:
a < 40

In [ ]:
# a배열에서 40보다 작은 데이터만 추출하려면 인덱스에서 식을 사용
a[a<40]

In [ ]:
a * b # 요소별 곱

### 2) 행렬의곱(@, dot함수) cf.* (요소별곱)

In [ ]:
A = np.array([[1,1],
             [0,1]])
B = np.array([[2,0],
             [3,4]])
A, B

In [ ]:
print('요소별 곱 A*B =', A*B, sep='\n')
print('행렬 곱 A@B=',A@B, sep='\n')
print('행렬 곱 A.dot(B)=',A.dot(B), sep='\n')

In [ ]:
A = np.array([[1,0],
             [0,1]])
B = np.array([[2,0],
             [3,4]])

In [ ]:
print('B@단위행렬=', B@A, sep='\n')

In [ ]:
print('단위행렬@B=', A@B, sep='\n')

### 3) 복합 대입 연산자 사용 (-=,+=....)

In [ ]:
a = np.ones( (2,3), dtype=int ) # 2행 3열짜리 int32배열
a

In [ ]:
b = np.random.random( (2,3) ) # 2행 3열짜리 float64 배열
b

In [ ]:
a += 3 # a = a+3
a

In [ ]:
b += a # b = b+a
b

In [ ]:
a += b # a = a+b
a

### 4) 배열 요소별 집계
- sum, min, max, mean, var(분산), std(표준편차)

In [14]:
a = np.array([[2,2,2,3],
             [4,3,2,1]])
a

array([[2, 2, 2, 3],
       [4, 3, 2, 1]])

In [15]:
print('전체 합 :', a.sum(), np.sum(a))
print('전체 평균', a.mean(), np.mean(a))
print('전체 최소값', a.min(), np.min(a))
print('전체 최대값', a.max(), np.max(a))
print('전체 분산', a.var(), np.var(a))
print('전체 표준편차', a.std(), np.std(a))

전체 합 : 19 19
전체 평균 2.375 2.375
전체 최소값 1 1
전체 최대값 4 4
전체 분산 0.734375 0.734375
전체 표준편차 0.8569568250501305 0.8569568250501305


### 5) 배열 축별 집계
- 축별 sum, min, max, mean, var(분산), std(표준편차), argmax

In [16]:
a

array([[2, 2, 2, 3],
       [4, 3, 2, 1]])

In [ ]:
# axis=1(1축) 들의 합
print('a 행별 합 :', a.sum(axis=1), np.sum(a, axis=1))

In [ ]:
# 열을 고정하고, 0축의 합
print('a 열별 합 :', a.sum(axis=0), np.sum(a, axis=0))

In [ ]:
print('a 행별 최대값 :', a.max(axis=1), np.max(a, axis=1))
print('a 열별 최대값 :', a.max(axis=0), np.max(a, axis=0))

In [ ]:
print('a 행별 최대값 위치 :', a.argmax(axis=1), np.max(a, axis=1))
print('a 열별 최대값 위치 :', a.argmax(axis=0), np.max(a, axis=0))

In [ ]:
a = np.array([[2,2,2,3],
             [4,3,2,1]])
a

In [ ]:
a

In [13]:
print('a 행별 최대값 위치 :', a.argmax(axis=1))

a 행별 최대값 위치 : [2 2 2 2 2]


In [18]:
# 3차원 배열의 집계
import numpy as np
b = np.arange(24).reshape(2, 3, 4) # [2면, 3행, 4열]
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [19]:
b.sum(), b.min(), b.max(), b.mean(), b.std(), b.var() # 배열 전체에 대한 집계값

(276, 0, 23, 11.5, 6.922186552431729, 47.916666666666664)

In [20]:
# 분산에 루트 씌우면 표준편차 
import math
math.sqrt(b.var()) # math.sqrt() : 스칼라 값에 루트 씌운 값

6.922186552431729

In [21]:
np.sum(b, axis=0) # 행과 열을 고정으로하고 0축들을 합 0,0,0+1,0,0

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [22]:
np.sum(b, axis=1) # 면과 열은 고정으로 하고 1축들을 합 0,0,0 + 0,1,0+0,0+0,3,0

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [23]:
np.sum(b, axis=2) #면, 행은 고정으로 하고, 2축들을 합

array([[ 6, 22, 38],
       [54, 70, 86]])

## 2.8 그 외 요소별 계산하는 범용함수들

- 출력 인수를 사용하면 메모리를 더 효율적으로 사용할 수 있음 

- np.sqrt(배열) : 제곱근 / math.sqrt(스칼라변수) 
- np.add(배열A, 배열B, 출력C) : C=np.add(A,B)와 동일
- np.multiply(A, B, C) : C = A*B 와 동일
- np.subtract(A, B, C) : 

In [24]:
a = np.array([1,2])
b = np.array([3,4])
c = np.empty((2))
a, b, c

(array([1, 2]), array([3, 4]), array([ 1.01775229e-265, -2.68549920e+276]))

In [28]:
np.add(a, b, c) #c는 출력인수 / c = np.add(a,b) / c = a+b 
c

array([4, 6])

In [31]:
a = np.array([1, 4, 9, 16])
b = np.empty(4)
np.sqrt(a, b) # math.sqrt(a) 불가 스칼라 변수만 가능
b

array([1., 2., 3., 4.])

In [32]:
# 메모리 사용량과 속도 측정해주는 메모리 프롸일러를 로드
# 아나콘다 프롬프트에서 pip install memory_profiler
%load_ext memory_profiler
A = np.random.randn(100000000) # 1억개 요소
B = np.random.randn(100000000)
C = np.random.randn(100000000)

In [ ]:
# %%time : 셀을 실행할 때 소요시간 출력
# %memit : 메모리 사용량 출력

In [34]:
%%time
%memit G = A*B + C
print(G)

peak memory: 4571.55 MiB, increment: 1400.07 MiB
[-0.23651512 -0.97099491 -1.66230859 ...  1.45454498  1.2721401
 -0.8203474 ]
CPU times: total: 844 ms
Wall time: 1.7 s


In [35]:
%%time
%memit T = A*B; G = T+C; del T
print(G)

peak memory: 4567.27 MiB, increment: 1395.79 MiB
[-0.23651512 -0.97099491 -1.66230859 ...  1.45454498  1.2721401
 -0.8203474 ]
CPU times: total: 859 ms
Wall time: 1.7 s


In [37]:
%%time
%memit G =A*B; G+=C
print(G)

peak memory: 3880.71 MiB, increment: 709.20 MiB
[-0.23651512 -0.97099491 -1.66230859 ...  1.45454498  1.2721401
 -0.8203474 ]
CPU times: total: 531 ms
Wall time: 1.39 s


In [38]:
%%time
%memit np.multiply(A, B, G); np.add(G, C, G)
print(G)

peak memory: 3161.88 MiB, increment: 0.00 MiB
[-0.23651512 -0.97099491 -1.66230859 ...  1.45454498  1.2721401
 -0.8203474 ]
CPU times: total: 312 ms
Wall time: 1.18 s


## 2.9 브로드 캐스팅
- 서로 다른 크기의 배열간 연산을 수행할 수 있도록 해주는 강력한 기능

In [39]:
# 2차원 배열인 경우
a = np.array([ [0,0,0],
             [10,10,10],
             [20,20,20],
             [30,30,30],])
b = np.array([0,1,2]) # 3열짜리 1차원
np.add(a,b), np.multiply(a,b)

(array([[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22],
        [30, 31, 32]]),
 array([[ 0,  0,  0],
        [ 0, 10, 20],
        [ 0, 20, 40],
        [ 0, 30, 60]]))

In [40]:
a = np.array([0,10,20,30])
b = np.array([1,2,3])

In [46]:
from numpy import newaxis
# np.newaxis 연산자를 이용해서 배열에 새로운 축을 추가하여 2차원
A = a[:, newaxis]
A

array([[ 0],
       [10],
       [20],
       [30]])

In [47]:
print(A + b)
print(np.add(A, b))

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


# 3절. 배열합치기/배열분리하기
- 인덱싱과 슬라이싱 : 특정한 값을 출력하겠다 하면 사용 단 슬라이싱을 사용함
- 두배열을 합치는 함수 
- r_, c_ 라는 객채를 사용
- 하나의 배열을 여러개 작은 배열로 분리하는 함수 
## 3.1 인덱싱과 슬라이싱
- 교안 pdf 31page
- [인덱싱 docs](https://docs.scipy.org/doc/numpy/user/basics.indexing.html)
- [배열 인덱싱 docs](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)
- [newaxis](https://docs.scipy.org/doc/numpy/reference/constants.html#numpy.newaxis)

In [48]:
a = np.arange(10)*3
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [51]:
# 인덱싱 : 없는 인덱싱 사용시 에러
a[2], a[-1]

(6, 27)

In [50]:
a[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [52]:
#슬라이싱 : 없는 인덱스 값도 가능
a[1:9:2]

array([ 3,  9, 15, 21])

In [53]:
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [54]:
a[::2] = 99
a

array([99,  3, 99,  9, 99, 15, 99, 21, 99, 27])

In [55]:
a[:100]

array([99,  3, 99,  9, 99, 15, 99, 21, 99, 27])

In [57]:
b = np.arange(20).reshape(5,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [58]:
b[1,2]

6

In [59]:
b[:, 0:-1] # 모든 행의 마지막 열 앞까지(종속변수를 제외하는 용도)

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18]])

In [66]:
b[:, -1:] # 모든행의 마지막 열만 추출(종속변수 추출하는 용도)

array([[ 3],
       [ 7],
       [11],
       [15],
       [19]])

In [67]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [88]:
# 0~1행까지 모든 열 추출(열을 생략할 경우 모든 열)
b[0:2], b[0:2,], b[0:2, :], b[:2], b[0:2, ...]

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[0, 1, 2, 3],
        [4, 5, 6, 7]]))

In [97]:
# 전체행의 맨 마지막열 추출(종속변수 추출하는 용도)
# 선행축은 생략 불가
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [95]:
b[...,-1]

array([ 3,  7, 11, 15, 19])

In [ ]:
# 모든행의 마지막 열을 추출해서 2차원으로 변경(5열 ->5행1열)

In [100]:
b[:,-1][:, newaxis]

array([[ 3],
       [ 7],
       [11],
       [15],
       [19]])

In [101]:
b[..., -1].reshape(5,1)

array([[ 3],
       [ 7],
       [11],
       [15],
       [19]])

In [107]:
b[1:-1, 1:-1], b[1:4, 1:-1]

(array([[ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 5,  6],
        [ 9, 10],
        [13, 14]]))

In [108]:
# 3차원 배열의 인덱싱, 슬라이싱
c = np.arange(24).reshape(2, 3, 4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [110]:
c[1,1,1]

17

In [112]:
# 선행축은 생략불가, 후행축은 생략 가능
c[0], c[0,], c[0,...]

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [115]:
# 1면 0행 모든 열을 출력하시오
c[1,0]

array([12, 13, 14, 15])

In [117]:
# 1면 모든 행의 
c[1,...,1]

array([13, 17, 21])

In [122]:
c[:, 0:2, 1:3]

array([[[ 1,  2],
        [ 5,  6]],

       [[13, 14],
        [17, 18]]])

## 3.2 두 배열을 쌓아 합치는 함수
**- vstack(tup) : 아래에 추가하는 방식으로 쌓아 합침**<br>
**- hstack(tup) : 옆으로 추가하는 방식으로 합침**<br>
**- dstack(tup) : 마지막 축(열)을 쌓아 합침. depth방향으로 합치는 함수(차원증가)<br>

In [124]:
c = np.array([1,2,3])
d = np.array([4,5,6])
v = np.vstack( (c,d) )
print('vstack 아래로 합치기 :', v, v.shape, sep='\n')
h = np.hstack( (c,d) )
print('hstack 옆으로 합치기 :', h, h.shape, sep='\n')
d = np.dstack( (c,d) )
print('dstack 축을 depth로 합치기 :', d, d.shape, sep='\n')

vstack 아래로 합치기 :
[[1 2 3]
 [4 5 6]]
(2, 3)
hstack 옆으로 합치기 :
[1 2 3 4 5 6]
(6,)
dstack 축을 depth로 합치기 :
[[[1 4]
  [2 5]
  [3 6]]]
(1, 3, 2)


In [126]:
c = np.arange(24).reshape(2, 3, 4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [128]:
a, b = c[0], c[1]
a, b

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [129]:
# 수직으로 합치기
np.vstack( (a, b))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [130]:
np.hstack( (a, b))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [133]:
np.dstack( (a,b))

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [134]:
np.concatenate((a,b), axis=0) # axis=0 : 기본값

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [135]:
np.concatenate((a, b), axis=1)

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [136]:
a, b

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

**- column_stack(tup) : 1차원 배열 을 2차원 배열의  열 단위로 합침**<br>
**- row_stack(tup) : 행단위로 합침 == vstack() 비슷**

In [139]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([9,10,11,12])
np.column_stack((a,b,c))

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [140]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [141]:
np.row_stack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [142]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- stack(tup, axis=n) : axis 속성에 따라 배열을 합침. axis 음수차원이 가능
- axis=0: 첫번째 차원, axis=-1이면 마지막차원(열)

In [144]:
a = np.arange(12).reshape(3,4)
b = np.arange(12,24).reshape(3,4)
a, b

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [145]:
np.stack((a, b), axis=0) # 0면에 a, 1면에 b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [146]:
np.stack((a, b), axis=1) # 행(1축)끼리 합쳐 면을 이룸

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [148]:
np.stack((a, b), axis=-1) # 열끼리 합쳐서 면을 이룸

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

## 3.3 r_,c_
- 나열 객체

In [149]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([9,10,11,12])

In [150]:
np.r_[a,b,c] # 한행

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [151]:
np.c_[a,b,c]

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [152]:
np.column_stack((a,b,c))

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

## 3.4 배열 분리하는 함수
- vsplit(ary, 정수 and 벡터data) : 첫번째 축(2차원의 경우 가로축)을 따라 분할
- hsplit(ary, 정수 and 벡터data) : 두번째 축(2차원의 경우 세로축)을 따라 분할
- dsplit(ary, 정수 and 벡터data) : depth를 따라 나눔. 3차원 이상에서만 동작
```
    정수 n : n개 분리
    [n] : n번째  인덱스를 기점으로 분리
    [n, m] : n번째, m번째 인덱스를 기점으로 분리
```

In [153]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [154]:
# 가로축을 따라 3개로 배열 분할. 분할 후에는 원래의 차원유지
a_vsplit = np.vsplit(a, 3)# 2개로 분리는 에러
a_vsplit

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [155]:
a_vsplit = np.vsplit(a, [2])
a_vsplit

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]])]

In [156]:
a_vsplit = np.vsplit(a, [1, 2])
a_vsplit

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [158]:
a_vsplit[0].ndim, a_vsplit[1].ndim, a_vsplit[2].ndim # 분할 후에도 차원수 유지

(2, 2, 2)

In [159]:
# dsplit은 3차원이상만 가능
b = np.arange(24).reshape(2, 3, 4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [160]:
b_vsplit = np.vsplit(b, 2) # 첫번째 축을 기준으로 2개로 분할
b_vsplit

[array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]]),
 array([[[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])]

In [161]:
b_hsplit = np.hsplit(b, 3)
b_hsplit

[array([[[ 0,  1,  2,  3]],
 
        [[12, 13, 14, 15]]]),
 array([[[ 4,  5,  6,  7]],
 
        [[16, 17, 18, 19]]]),
 array([[[ 8,  9, 10, 11]],
 
        [[20, 21, 22, 23]]])]

In [162]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

- split(ary, 갯수나 인덱스 벡터, axis=?)
    * axis=0 : vsplit()동일
    * axis=1 : hsplit()동일
    * axis=2 : 3차원 이상에서만 동장. dsplit(0동일

In [163]:
a = np.arange(20).reshape(2, 10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [164]:
np.split(a, 2, axis=1)

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19]])]