<b><font size="6" color="red">ch12. 데이터 프레임(2차원)과 시리즈(1차원)(Pandas)</font></b>
- pip install pandas

# 1절. 판다스 패키지
- 데이터 분석을 위해 반드시 알아야할 패키지. 넘파이를 기반으로 하며, 다른 많은 라이브러리와 잘 통합되도록 설계
- 1차원 구조를 갖는 시리즈, 2차원 구조를 갖는 데이터 프레임을 제공
- 판다스 장점 : 
```
데이터 프레임 생성, 파일io, 레이블링, 부분데이터추출, 크기 변경 (행이나 열삽입, 열삭제), 데이터 분할, 병합, 데이터 정렬, 결측치 처리, 피벗과 언피벗등에 용이 
```
- https://pypi.org/project/pandas/ (package index)
- https://pandas.pydata.org/docs/getting_started/index.html (API reference)

In [1]:
import pandas as pd
pd.__version__

'1.5.3'

In [5]:
data = pd.read_json('data/ch09_member1.json', encoding='cp949')
display(data)
print(type(data))

name  age    email address
0  홍길동   20  h@h.com      서울
1  김길동   25  k@h.com      대구
2  신길동   30  s@h.com      대전

<class 'pandas.core.frame.DataFrame'>


In [8]:
member4 = pd.read_csv('data/ch09_member4.csv')
member4.head() # 최초 상위 5개 행을 출력

Name  Age             Email  Address
0  홍길동   20  kildong@hong.com  서울시 관악구
1  신길동   25  sindong@hong.com  서울시 동작구
2  김길동   30  kimdong@hong.com  서울시 금천구
3  홍길동   20  kildong@hong.com  서울시 관악구
4  신길동   25  sindong@hong.com  서울시 동작구

In [14]:
member1 = pd.read_csv('data/ch09_member1.csv', header=None,
                     names=['name','age','email','address'])
member1

name  age             email  address
0  홍길동   20  kildong@hong.com  서울시 관악구
1  김길동   25  kimdong@hong.com  서울시 동작구
2  신길동   21  sindong@hong.com  서울시 금천구

In [15]:
iris = pd.read_hdf('data/ch09_iris2.hdf5', key='iris')
iris

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

# 2절. 데이터 프레임 만들기
## 2.1 딕셔너리를 이용해서 데이터프레임 만들기

In [17]:
# value 값이  list인 딕셔너리를 데이터프레임으로 변환
d = {'kor':[100, 90],
    'mat':[95, 99]}
df = pd.DataFrame(data = d)
df

kor  mat
0  100   95
1   90   99

In [18]:
df.to_dict() # 데이터 프레임을 딕셔너리로

{'kor': {0: 100, 1: 90}, 'mat': {0: 95, 1: 99}}

In [19]:
df.to_numpy() # 데이터 프레임을 넘파이 배열

array([[100,  95],
       [ 90,  99]], dtype=int64)

In [20]:
# 딕셔너리 리스트를 데이터프레임으로
d = [{'kor':100, 'mat':95}, {'kor':90, 'mat':99}]
df = pd.DataFrame(data=d)
df

kor  mat
0  100   95
1   90   99

In [21]:
df.dtypes

kor    int64
mat    int64
dtype: object

In [23]:
df.info() # ★★★★★★★★★★★★★★★★★★★★

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   kor     2 non-null      int64
 1   mat     2 non-null      int64
dtypes: int64(2)
memory usage: 160.0 bytes


In [25]:
df.dtypes.to_dict()

{'kor': dtype('int64'), 'mat': dtype('int64')}

In [26]:
df['kor']

0    100
1     90
Name: kor, dtype: int64

In [29]:
import numpy as np
df['kor'].astype(np.float64)

0    100.0
1     90.0
Name: kor, dtype: float64

In [30]:
d = [{'kor':100, 'mat':100}, {'kor':90, 'mat':99}, {'kor':83, 'eng':85}]
df = pd.DataFrame(data = d)
df

kor    mat   eng
0  100  100.0   NaN
1   90   99.0   NaN
2   83    NaN  85.0

In [31]:
type(np.nan)

float

In [ ]:
df['mat'].astype(np.int32) # 결측치는 int로 형변환 불가 (결측지를 대체값으로 치환 후 변환)

## 2.2리스트를 이용하여 데이터 프레임 만들기

In [32]:
kor = [100,90,95,90,65]
mat = [25,96,29,48,96]
df = pd.DataFrame({'kor':kor, 'mat':mat})
df

kor  mat
0  100   25
1   90   96
2   95   29
3   90   48
4   65   96

In [35]:
np.c_[kor, mat]

array([[100,  25],
       [ 90,  96],
       [ 95,  29],
       [ 90,  48],
       [ 65,  96]])

In [38]:
df = pd.DataFrame(np.c_[kor, mat], columns=['kor','mat']) # 한글도 가능
df

kor  mat
0  100   25
1   90   96
2   95   29
3   90   48
4   65   96

In [40]:
l = [[100,90],[10,20]]
df = pd.DataFrame(l, columns=['국어','수학'])
df

국어  수학
0  100  90
1   10  20

In [44]:
df = pd.read_csv(r'D:\ai\Downloads\shareData\소상공인시장진흥공단_상가(상권)정보_20240930\소상공인시장진흥공단_상가(상권)정보_세종_202409.csv',
                encoding='utf-8', sep=',', low_memory=False, nrows=30)
df.shape

(30, 39)

In [46]:
df.head(1)

상가업소번호       상호명  지점명 상권업종대분류코드 상권업종대분류명 상권업종중분류코드 상권업종중분류명  \
0  MA0101202210A0084499  베트남쌀국수퍼짱  NaN        I2       음식      I205    동남아시아   

  상권업종소분류코드 상권업종소분류명 표준산업분류코드  ...                     건물관리번호    건물명  \
0    I20501  베트남식 전문   I56194  ...  3611010700103610086000001  모닝시티2   

                       도로명주소     구우편번호  신우편번호  동정보  층정보  호정보         경도  \
0  세종특별자치시 세종특별자치시 한누리대로 311  339003.0  30123  NaN  1.0  NaN  127.25584   

          위도  
0  36.492065  

[1 rows x 39 columns]

In [49]:
# 판다스 디스플레이 옵션
pd.options.display.max_columns = 39 # 39열까지 display 가능
pd.options.display.max_rows = 40 # 40행까지 display 가능
df.head(1)

상가업소번호       상호명  지점명 상권업종대분류코드 상권업종대분류명 상권업종중분류코드 상권업종중분류명  \
0  MA0101202210A0084499  베트남쌀국수퍼짱  NaN        I2       음식      I205    동남아시아   

  상권업종소분류코드 상권업종소분류명 표준산업분류코드          표준산업분류명  시도코드      시도명  시군구코드     시군구명  \
0    I20501  베트남식 전문   I56194  김밥 및 기타 간이 음식점업    36  세종특별자치시  36110  세종특별자치시   

      행정동코드 행정동명       법정동코드 법정동명                 지번코드  대지구분코드 대지구분명  지번본번지  \
0  36110518  나성동  3611010700  나성동  3611010700107320000       1    대지    732   

   지번부번지                     지번주소         도로명코드                    도로명  건물본번지  \
0    NaN  세종특별자치시 세종특별자치시 나성동 732  361102000002  세종특별자치시 세종특별자치시 한누리대로    311   

   건물부번지                     건물관리번호    건물명                      도로명주소  \
0    NaN  3611010700103610086000001  모닝시티2  세종특별자치시 세종특별자치시 한누리대로 311   

      구우편번호  신우편번호  동정보  층정보  호정보         경도         위도  
0  339003.0  30123  NaN  1.0  NaN  127.25584  36.492065

## 2.3 read_csv

In [50]:
# (1) CSV 파일 불러오기
member = pd.read_csv('data/ch12_member.csv')
member

Name  Age          Email  Address       Birth
0   홍길동   20  hong@hong.com  서울시 강동구  1999-01-01
1   홍길서   30   seo@hong.com  서울시 강서구  1989-01-01
2   홍길남   22   nam@hong.com  서울시 강남구  1997-01-01
3   홍길북   60   buk@hong.com  서울시 강북구  1959-01-01
4   홍길중   40   mid@hong.com   부산시 중구  1979-01-01
5  #홍길뜽   24    non@not.com      없는구  2000-01-01

In [51]:
member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Name     6 non-null      object
 1   Age      6 non-null      int64 
 2   Email    6 non-null      object
 3   Address  6 non-null      object
 4   Birth    6 non-null      object
dtypes: int64(1), object(4)
memory usage: 368.0+ bytes


In [52]:
# 문자로 읽어들인 Birth를 datetime형으로 바꾸는 방법
# 형 변환은 astype()쓰지만 datetime형으로 변환할 때는 to_datetime()함수 사용
member['Birth'] = pd.to_datetime(member['Birth'])
member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype         
---  ------   --------------  -----         
 0   Name     6 non-null      object        
 1   Age      6 non-null      int64         
 2   Email    6 non-null      object        
 3   Address  6 non-null      object        
 4   Birth    6 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 368.0+ bytes


In [54]:
import numpy as np
member['Age'].astype(np.int16)
member.dtypes

Name               object
Age                 int64
Email              object
Address            object
Birth      datetime64[ns]
dtype: object

In [57]:
# (2) 특정행 제외하고 csv파일 읽어오기
member = pd.read_csv('data/ch12_membercp949.csv', encoding='cp949', skiprows=[1,6])
member # 1,6번째 행 제외하고 읽어오기 (시작이 1부터)

Name  Age         Email  Address       Birth
0  홍길서   30  seo@hong.com   서울시 중구  1999-12-01
1  홍길남   21  nam@hong.com  서울시 강동구  1999-11-01
2  홍길북   22  buk@hong.com  서울시 관악구  1999-05-01
3  홍길중   23  mid@hong.com  부산시 강동구  1999-01-30

In [58]:
member_df = pd.read_csv('data/ch12_membersep.csv', sep='|', nrows=5)
member_df

Name  Age          Email  Address       Birth
0  홍길동   20  hong@hong.com  서울시 강동구  1999-01-01
1  홍길서   30   seo@hong.com  서울시 강서구  1989-01-01
2  홍길남   22   nam@hong.com  서울시 강남구  1997-01-01
3  홍길북   60   buk@hong.com  서울시 강북구  1959-01-01
4  홍길중   40   mid@hong.com   부산시 중구  1979-01-01

In [59]:
# 주석제외, datetime형 필드 지정하여 읽어오기
member_df = pd.read_csv('data/ch12_membertab.csv', sep='\t', comment='#',
                       parse_dates=['Birth'])
member_df # #이 있는 행은 제외하고 읽어오기

Name  Age          Email  Address       Birth
0   홍길동   20  hong@hong.com  서울시 강동구  1999-01-01
1   홍길서   30   seo@hong.com  서울시 강서구  1989-01-01
2   홍길남   22   nam@hong.com  서울시 강남구  1997-01-01
3   홍길북   60   buk@hong.com  서울시 강북구  1959-01-01
4  홍길중    40   mid@hong.com   부산시 중구  1979-01-01

## iris 데이터 가져오기 방법1 : sklearn(머신러닝패키지)
## iris 데이터 가져오기 방법2 : statsmodels(R데이터 가져오기)
## iris 데이터 가져오기 방법3 : seaborn(시각화 패키지)

## 2.4 sklearn.datasets 모듈 데이터(iris)를 데이터 프레임으로 변환

In [60]:
from sklearn import datasets
# import sklearn.datasets as datasets
# sklearn 패키지는 머신러닝을 공부하기 위한, 학습 데이터셋들을 제공
# sklearn 패키지에서 제공되는 데이터셋들은 딕셔너리 형식으로 제공
iris = datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [61]:
print(iris.DESCR) # iris 데이터 셋에 대한 설명

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [62]:
iris.data # 독립변수
iris['data'][:3]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [64]:
iris.feature_names
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [66]:
# 데이터 프레임에서 열이름
[col[:-4].strip().replace(' ','_')for col in iris.feature_names]

['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

In [68]:
#
[col[:12].strip().replace(' ','_') for col in iris.feature_names]

['sepal length', 'sepal width', 'petal length', 'petal width']

In [69]:
iris.target
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [70]:
iris.target_names
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [73]:
# 데이터 프레임의 가장 오른쪽 열
iris.target_names[iris.target]
iris['target_names'][iris['target']]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [74]:
# 독립변수
data = iris.data
print(data[:5])
# 종속변수
target = iris.target_names[iris.target].reshape(-1, 1)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [75]:
print('독립변수 차원 :', data.shape)
print('종속변수 차원 :', target.shape)

독립변수 차원 : (150, 4)
종속변수 차원 : (150, 1)


In [76]:
np.hstack((data, target))

array([['5.1', '3.5', '1.4', '0.2', 'setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'setosa'],
       ['5.4', '3.9', '1.7', '0.4', 'setosa'],
       ['4.6', '3.4', '1.4', '0.3', 'setosa'],
       ['5.0', '3.4', '1.5', '0.2', 'setosa'],
       ['4.4', '2.9', '1.4', '0.2', 'setosa'],
       ['4.9', '3.1', '1.5', '0.1', 'setosa'],
       ['5.4', '3.7', '1.5', '0.2', 'setosa'],
       ['4.8', '3.4', '1.6', '0.2', 'setosa'],
       ['4.8', '3.0', '1.4', '0.1', 'setosa'],
       ['4.3', '3.0', '1.1', '0.1', 'setosa'],
       ['5.8', '4.0', '1.2', '0.2', 'setosa'],
       ['5.7', '4.4', '1.5', '0.4', 'setosa'],
       ['5.4', '3.9', '1.3', '0.4', 'setosa'],
       ['5.1', '3.5', '1.4', '0.3', 'setosa'],
       ['5.7', '3.8', '1.7', '0.3', 'setosa'],
       ['5.1', '3.8', '1.5', '0.3', 'setosa'],
       ['5.4', '3.4', '1.7', '0.2', 'setosa'],
       ['5.1'

In [77]:
pd.DataFrame(np.hstack((data, target)), columns=[col[:12].strip().replace(' ','_')for col in iris.feature_names]+['spacies'])

sepal_length sepal_width petal_length petal_width    spacies
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [79]:
df = pd.DataFrame(np.hstack((data, target)),
                 columns=iris.feature_names + ['spacies'])
df.head()

sepal length (cm) sepal width (cm) petal length (cm) petal width (cm)  \
0               5.1              3.5               1.4              0.2   
1               4.9              3.0               1.4              0.2   
2               4.7              3.2               1.3              0.2   
3               4.6              3.1               1.5              0.2   
4               5.0              3.6               1.4              0.2   

  spacies  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [81]:
df.spacies #df['spacies']


0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: spacies, Length: 150, dtype: object

In [82]:
df['sepal length (cm)']
# df.sepal length (cm) 열이름에 space나 특수문자의 경우 . 열접근이 불가

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal length (cm), Length: 150, dtype: object

In [85]:
# ⓑ 독립변수, 종속변수를 따로 데이터프레임으로 만들고 두 데이터 프레임을 연결
X = pd.DataFrame(iris.data, columns=iris.feature_names) # X : 독립변수
X.head(1)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2

In [87]:
X.columns = [col[:15].strip().replace(' ','_') for col in iris.feature_names]

In [88]:
X.head(1)

sepal_length_(c  sepal_width_(cm  petal_length_(c  petal_width_(cm
0              5.1              3.5              1.4              0.2

In [90]:
# y:종속변수 데이터 프레임
y = pd.DataFrame(iris.target_names[iris.target], columns=['species'])
y

species
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
..         ...
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 1 columns]

In [92]:
print(X.index) # index : 행이름
print(y.index)

RangeIndex(start=0, stop=150, step=1)
RangeIndex(start=0, stop=150, step=1)


In [93]:
# 데이터 프레임 연결하기 (열로 연결)
iris_df = pd.concat( [X, y], axis=1)
iris_df

sepal_length_(c  sepal_width_(cm  petal_length_(c  petal_width_(cm  \
0                5.1              3.5              1.4              0.2   
1                4.9              3.0              1.4              0.2   
2                4.7              3.2              1.3              0.2   
3                4.6              3.1              1.5              0.2   
4                5.0              3.6              1.4              0.2   
..               ...              ...              ...              ...   
145              6.7              3.0              5.2              2.3   
146              6.3              2.5              5.0              1.9   
147              6.5              3.0              5.2              2.0   
148              6.2              3.4              5.4              2.3   
149              5.9              3.0              5.1              1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [94]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   sepal_length_(c  150 non-null    float64
 1   sepal_width_(cm  150 non-null    float64
 2   petal_length_(c  150 non-null    float64
 3   petal_width_(cm  150 non-null    float64
 4   species          150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


## 2.5 statsmodels 패키지의 iris

In [96]:
# iris 데이터 가져오기 방법2
import statsmodels.api as sm
iris_data = sm.datasets.get_rdataset('iris', package='datasets', cache=True)
iris_data

<class 'statsmodels.datasets.utils.Dataset'>

In [97]:
iris = iris_data.data
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
iris['Sepal.Length']
# iris.Sepal.Length 열 이름에 . 이 있으면 iris.Sepal.Length로 접근 불가

In [101]:
iris.columns = [col.replace('.', '') for col in iris.columns]
iris.head(1)

SepalLength  SepalWidth  PetalLength  PetalWidth Species
0          5.1         3.5          1.4         0.2  setosa

In [104]:
[col.lower().replace('.','_') for col in iris.columns]

['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species']

## 2.6 seaborn 패키지의 iris

In [105]:
# iris 데이터 가져오기 방법3 : seaborn
import seaborn as sns
iris = sns.load_dataset('iris')
iris.head(1)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa

In [107]:
# 데이터 프레임을 파일로 출력
iris.to_csv('data/ch12_iris.csv', sep=',', mode='w', encoding='utf-8',
           index=False)

In [108]:
iris.to_csv('data/ch12_iris.csv.gz',
           index=False,
           compression='infer')

In [109]:
read_iris = pd.read_csv('data/ch12_iris.csv.gz', compression='infer')
read_iris.head(1)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa

In [110]:
member.columns

Index(['Name', 'Age', 'Email', 'Address', 'Birth'], dtype='object')

In [111]:
member.columns = ['이름','나이','메일','주소','생년월일']
member

이름  나이            메일       주소        생년월일
0  홍길서  30  seo@hong.com   서울시 중구  1999-12-01
1  홍길남  21  nam@hong.com  서울시 강동구  1999-11-01
2  홍길북  22  buk@hong.com  서울시 관악구  1999-05-01
3  홍길중  23  mid@hong.com  부산시 강동구  1999-01-30

## 3.2행이름 지정

In [114]:
member.index

RangeIndex(start=0, stop=4, step=1)

In [115]:
member

이름  나이            메일       주소        생년월일
0  홍길서  30  seo@hong.com   서울시 중구  1999-12-01
1  홍길남  21  nam@hong.com  서울시 강동구  1999-11-01
2  홍길북  22  buk@hong.com  서울시 관악구  1999-05-01
3  홍길중  23  mid@hong.com  부산시 강동구  1999-01-30

In [125]:
member.index = range(10,14)
member

이름  나이            메일       주소        생년월일
10  홍길서  30  seo@hong.com   서울시 중구  1999-12-01
11  홍길남  21  nam@hong.com  서울시 강동구  1999-11-01
12  홍길북  22  buk@hong.com  서울시 관악구  1999-05-01
13  홍길중  23  mid@hong.com  부산시 강동구  1999-01-30

In [127]:
member['이름']

10    홍길서
11    홍길남
12    홍길북
13    홍길중
Name: 이름, dtype: object

In [123]:
member.loc['서','이름']

KeyError: '서'